### PR TITLE
Add lando.yml allowing run laminas-mvc-skeleton with lando.

### PR DESCRIPTION
**Pull request by thalles**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description
Lando it's a free, open source, cross-platform, local development environment and DevOps tool built on Docker container technology and developed by Tandem. Designed to work with most major languages, frameworks and services, Lando provides an easy way for developers of all skill levels to specify simple or complex requirements for their projects, and then quickly get to work on them.

Related pages: 
- https://docs.lando.dev/getting-started/
- https://github.com/lando/lando

**PS: If you intend to accept this PR I can update the documentation in README.md.**

Thanks in advanced!

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Personally not in favor of this: Lando is an opinionated skeleton on top of docker compose, and from personal experience, it usually lives in projects that I touch for 1 to 2 weeks max, before being ripped out for more flexibility and to align to production.

A very minimal `docker-compose.yml` would be preferable here.

In addition to that:

 * no PHPMyAdmin, please: would be best to connect to MySQL directly
 * no MySQL in general is also preferable: PostgreSQL and similar should be endorsed for new users, but the skeleton does not require a DB anyway to run

**Comment by thalles** [comment]
We can let commented some options like database settings.

**Comment by ThallesVFS** [comment]
I should go head?

**Comment by Ocramius** [comment]
IMO okay with a very minimal docker-compose

**Pull request closed without merging**
