### PR TITLE
update php requirement to 7.3

### PR DESCRIPTION
**Pull request by samsonasik**
Based on @froschdesign comment at https://github.com/laminas/tutorials/pull/18#discussion_r407025086

### CODE REVIEW

**Comment by michalbundyra** [comment]
We do not have any clear policy about skeleton.
I think it might be better to use even PHP 7.3, because:
- PHP 7.2 is security only
- vagrant and docker configuration (in that project) use PHP 7.3
- we have already some components on PHP 7.3

Thoughts?

**Comment by samsonasik** [comment]
I'm ok with php 7.3 /cc @froschdesign

**Comment by samsonasik** [comment]
@michalbundyra I've updated to php 7.3

**Comment by michalbundyra** [comment]
Thanks, @samsonasik! 

Now we just need update tutorials... :)

**Comment by samsonasik** [comment]
@michalbundyra I created PR https://github.com/laminas/tutorials/pull/19 for that.

**Comment by alexivaylov** [comment]
Guys, I totally forgot about this:
https://www.zend.com/services/php-long-term-support#
Do you think it will be a problem?

**Pull request merged**
