### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by AdeMS**
Fix installing Laminas MVC Skeleton with laminas-log

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by froschdesign** [comment]
@AdeMS 
> Fix installing Laminas MVC Skeleton with laminas-log

Can you describe the problem you have?
Thanks in advance! 👍🏻

**Comment by AdeMS** [comment]
Sorry, for there is no explanation previously.

On fresh installment with
`$ composer create-project -s dev laminas/laminas-mvc-skeleton path/to/install`

If you choose to install all optional packages, there is a dependencies version conflict between laminas/laminas-log with psr/log

`        Do you want a minimal install (no optional packages)? Y/n
n

    Would you like to install the developer toolbar? y/N
y
    Will install laminas/laminas-developer-tools (^2.8.0)
    When prompted to install as a module, select development.config.php.dist

    Would you like to install database support (installs laminas-db)? y/N
y
    Will install laminas/laminas-db (^2.17.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install forms support? y/N
y
    Will install laminas/laminas-mvc-form (^2.0.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install JSON de/serialization support? y/N
y
    Will install laminas/laminas-json (^3.5.0)

    Would you like to install logging support? y/N
y
    Will install laminas/laminas-log (^2.16.1)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install command-line interface support? y/N
y
    Will install laminas/laminas-cli (^1.8.0)

    Would you like to install i18n support? y/N
y
    Will install laminas/laminas-mvc-i18n (^1.7.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install the official MVC plugins, including PRG support, identity, and flash messages? y/N
y
    Will install laminas/laminas-mvc-plugins (^1.2.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to use the PSR-7 middleware dispatcher? y/N
y
    Will install laminas/laminas-mvc-middleware (^2.3.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install sessions support? y/N
y
    Will install laminas/laminas-session (^2.16.0)
    When prompted to install as a module, select application.config.php or modules.config.php

    Would you like to install the laminas-di for laminas-servicemanager? y/N
y
    Will install laminas/laminas-di (^3.12.0)
    When prompted to install as a module, select application.config.php or modules.config.php
Updating root package
    Running an update to install optional packages
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-log[2.16.1, ..., 2.17.0] require psr/log ^1.1.2 -> found psr/log[1.1.2, 1.1.3, 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laminas/laminas-log ^2.16.1 -> satisfiable by laminas/laminas-log[2.16.1, 2.17.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
Error installing optional packages. Run with verbosity to debug
> php bin/clear-config-cache.php
Configured config cache file 'data/cache/module-config-cache.application.config.cache.php' not found
No security vulnerability advisories found.
> laminas-development-mode enable
You are now in development mode.
> php bin/update-gitignore.php
> php -r 'if (file_exists("bin/remove-package-artifacts.php")) include "bin/remove-package-artifacts.php";'
`

**Comment by froschdesign** [comment]
Fixes with #87 and released with [version 2.4.0](https://github.com/laminas/laminas-mvc-skeleton/releases/tag/2.4.0).

**Comment by froschdesign** [comment]
@AdeMS 
Thanks anyway for pointing out the problem and your support! 👍🏻

**Pull request closed without merging**
