### PR TITLE
Fixes #6 - Invisible logo in Laminas MVC Skeleton

### LINKED ISSUE #6: Invisible logo in Laminas MVC Skeleton
### Bug Report

image

#### Summary

Can't see the logotype in top left corner of the dashboard.

#### Current behavior

Bad color scheme :)

#### How to reproduce

Install plain Laminas MVC skeleton

#### Expected behavior

Add some better background color to the logotype.

### PR DESCRIPTION
**Pull request by froschdesign**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### CODE REVIEW

**Comment by michalbundyra** [comment]
@froschdesign wouldn't be better to update the SVG file and here set just a colour instead of tricky filter+invert?

**Comment by froschdesign** [comment]
@michalbundyra 
I had the same thought but I know too little about the skeleton or its history. I dislike that we deliver another logo file with this repository. On the other hand, I like the fact that the skeleton requires no external resources.

Three options that come to my mind:

## 1. Option

We can use the CSS file and logo from docs.laminas.dev and the result will look like this:

localhost_8888_laminas-mvc-skeleton_public_-1

But this ends in external HTTP requests.

## 2. Option

We can [install Bootstrap via Composer](https://github.com/twbs/bootstrap/blob/master/composer.json) but this means we have to run a script to copy the files to the `public` directory. ([Composer can help here.](https://getcomposer.org/doc/articles/scripts.md#command-events)) 

The logo is delivered with this repository.

## 3. Option

We use [CDN from Bootstrap](https://www.bootstrapcdn.com/) or Google to include the CSS and JS and logo comes from docs.laminas.dev.

---

But the question is what is the best option for developers who start with the skeleton as basis for new application.
The Laminas logo and favicon will be deleted first. Why then integrate at all?

**Comment by michalbundyra** [comment]
@froschdesign 
> I dislike that we deliver another logo file with this repository. On the other hand, I like the fact that the skeleton requires no external resources.

I was asking about it long time ago, and if I remember correctly I got the answer that it's nice that all is included, so we can build some demo app and run it up when there is no internet connection etc. Not sure if it still the case.

I would just change the colour in svg file so we can easily modify it from css without filters :)

**Comment by froschdesign** [comment]
> The Laminas logo and favicon will be deleted first. Why then integrate at all?

I will answer to my own question: it's demonstrates the usage of integration a logo and a favicon. Therefore it should be included.

**Comment by michalbundyra** [comment]
Thanks, @froschdesign!

**Pull request merged**
